server:
  port: 8080
  
spring:
  application:
    name: student-server
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:alunodb   

disciplina-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:8080,localhost:28081
    ServerListRefreshInterval: 15000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
